# Generated by Django 3.0.8 on 2021-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210526_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
